### PR TITLE
fix ws context race

### PR DESCRIPTION
**Pull request by motopods-lucas**

### CODE REVIEW

**Comment by cah4a** [comment]
Hey @motopods-lucas 

Thanks for your contribution!
Sorry for late response, got lost in work. Will take a look during weekend.

**Comment by kevinmarrec** [comment]
Was going to ping owners about this one. it fixes issue https://github.com/cah4a/trpc-bun-adapter/issues/11 but I'm not sure about what it exactly fixes. It sounds like to be when `createContext` returns a promise and when there is multiple connections, some context race happens.

Still sounds like a good spot, even if would have be really cool to have a reproduction repository to play with the bug :)

**Comment by motopods-lucas** [comment]
@kevinmarrec  Due to the current bun adapter initializing the context in the websocket open event, if the asynchronous ctxPromise has not finished when the websocket receives the first message, client.data.handleRequest may not be assigned, causing an error. Therefore, it is necessary to ensure that ctxPromise has completed and the data in client.data is assigned before handling the message event. 

https://github.com/cah4a/trpc-bun-adapter/blob/3c001f8c8de1120eaaadb1b62c631eba34302623/src/e2e.test.ts#L11   just make a slow createContext, you will get the error.

**Comment by kevinmarrec** [comment]
@motopods-lucas Thank you very much for the explanation 🙏 Makes sense !

**Review by cah4a — APPROVED** [review]

**Pull request merged**
